apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lendsmart-app-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: lendsmart-app
    namespace: default
roleRef:
  kind: Role
  name: lendsmart-app-role
  apiGroup: rbac.authorization.k8s.io
