apiVersion: v1
kind: ServiceAccount
metadata:
    name: lendsmart-app
    namespace: default
    labels:
        app: lendsmart
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: lendsmart-db
    namespace: default
    labels:
        app: lendsmart
        component: database
